export const descontos = [
	{ regiao: "SUL", uf: "SC", opcaoDePagamento: "CREDITO", desconto: 0.06 },
	{ regiao: "SUL", uf: "SC", opcaoDePagamento: "PIX", desconto: 0.1 },
	{ regiao: "SUL", uf: "PR", opcaoDePagamento: "CREDITO", desconto: 0.06 },
	{ regiao: "SUL", uf: "PR", opcaoDePagamento: "PIX", desconto: 0.1 },
	{ regiao: "SUDESTE", uf: "SP", opcaoDePagamento: "CREDITO", desconto: 0.06 },
	{ regiao: "SUDESTE", uf: "SP", opcaoDePagamento: "PIX", desconto: 0.1 },
	{ regiao: "SUDESTE", uf: "RJ", opcaoDePagamento: "CREDITO", desconto: 0.06 },
	{ regiao: "SUDESTE", uf: "RJ", opcaoDePagamento: "PIX", desconto: 0.1 },
	{ regiao: "SUDESTE", uf: "MG", opcaoDePagamento: "CREDITO", desconto: 0.06 },
	{ regiao: "SUDESTE", uf: "MG", opcaoDePagamento: "PIX", desconto: 0.1 },
	{ regiao: "SUDESTE", uf: "ES", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORTE", uf: "AM", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORTE", uf: "PA", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORTE", uf: "AC", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORTE", uf: "RR", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORTE", uf: "RO", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORTE", uf: "AP", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORTE", uf: "TO", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "AL", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "BA", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "CE", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "MA", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "PB", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "PE", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "PI", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "RN", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{ regiao: "NORDESTE", uf: "SE", opcaoDePagamento: "CREDITO", desconto: 0.1 },
	{
		regiao: "CENTRO-OESTE",
		uf: "GO",
		opcaoDePagamento: "CREDITO",
		desconto: 0.1,
	},
	{
		regiao: "CENTRO-OESTE",
		uf: "MT",
		opcaoDePagamento: "CREDITO",
		desconto: 0.1,
	},
	{
		regiao: "CENTRO-OESTE",
		uf: "MS",
		opcaoDePagamento: "CREDITO",
		desconto: 0.1,
	},
	{
		regiao: "CENTRO-OESTE",
		uf: "DF",
		opcaoDePagamento: "CREDITO",
		desconto: 0.1,
	},
	{ regiao: "SUDESTE", uf: "ES", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORTE", uf: "AM", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORTE", uf: "PA", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORTE", uf: "AC", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORTE", uf: "RR", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORTE", uf: "RO", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORTE", uf: "AP", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORTE", uf: "TO", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "AL", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "BA", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "CE", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "MA", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "PB", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "PE", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "PI", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "RN", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "NORDESTE", uf: "SE", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "CENTRO-OESTE", uf: "GO", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "CENTRO-OESTE", uf: "MT", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "CENTRO-OESTE", uf: "MS", opcaoDePagamento: "PIX", desconto: 0.15 },
	{ regiao: "CENTRO-OESTE", uf: "DF", opcaoDePagamento: "PIX", desconto: 0.15 },
];
